### ISSUE TITLE
hadoop 개발 환경 구성

### ISSUE THREAD

**Issue by hyonaldo** [dkim010/lolminer#6]

**Comment by hyonaldo** [comment]
http://stackoverflow.com/questions/16775534/python-and-proxy-urllib2-urlerror-urlopen-error-errno-110-connection-timed

**Comment by hyonaldo** [comment]
c3 개발 환경 구성 작업 실패
다른 서버와 달리 아래와 같은 에러 발생
```
......
debug: http://xxx:8080/api/v1/clusters/c3.150909/configurations?type=mapred-site&tag=version1453785383531
Traceback (most recent call last):
  File "<stdin>", line 1081, in <module>
  File "<stdin>", line 1073, in main
  File "<stdin>", line 971, in make_configuration
  File "<stdin>", line 385, in parse
  File "/usr/lib64/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Comment by hyonaldo** [comment]
xbeta 4대에 따로 새 하둡 설치 하는 것도 방법~

**Comment by hyonaldo** [comment]
10번 서버를 namenode로 하둡 구성 시작
